### ISSUE TITLE
Iso not available for 7.7.0

### ISSUE THREAD

**Issue by Adre** [dotzero/vagrant-debian-wheezy-64#39]
Running the build results in the following error:

ERROR: MD5 does not match. Got 04f64d4ef6994944a4e8784c49a1c10d instead of 0b31bccccb048d20b551f70830bb7ad0. Aborting.

Checking the url in the script - http://cdimage.debian.org/debian-cd/7.7.0/amd64/iso-cd/debian-7.7.0-amd64-netinst.iso - results in a 404 error and looking at the site it seems like v7.7.0 is no longer available for download.

**Comment by dotzero** [comment]
Script already updated to 7.8.0

**Comment by Adre** [comment]
Looks like I cloned it the night before the update and didn't check again before I opened the ticket, sorry about that.
